import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/page/Header";
import Footer from "@/components/page/Footer";
import Container from "@/components/Container";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
         <Container>
          <Header />
          {children}
          <Footer />
          </Container>
      </body>
    </html>
  );
}
